# Generated by Django 5.1.1 on 2024-09-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Article title')),
                ('announcement', models.CharField(max_length=250, verbose_name='Article announcement')),
                ('full_text', models.TextField(verbose_name='Article text')),
                ('date', models.DateTimeField(verbose_name='Publication date')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
